services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: my-springboot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dockerdb
      - SPRING_DATASOURCE_USERNAME=docker_user
      - SPRING_DATASOURCE_PASSWORD=docker_password
    ports:
      - "8082:8080"
    depends_on:
      - db
      - seq   
 
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "80:80"  # Web UI
      - "5341:5341"  # Ingestion API
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    volumes:
      - seq-data:/data
      - seq-logs:/log

volumes:
  pgdata:
  seq-data:
  seq-logs: