name: CI Pipeline

# Trigger on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest # Use an Ubuntu environment for the runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build and run Docker Compose
      - name: Build and Run Docker Compose
        run: docker-compose up --build --detach

      # Step 5: Run tests
      # - name: Run Tests
      #   run: docker-compose exec app mvn test

      # Step 6: Upload Test Results (Always upload artifacts), Ensure artifacts are uploaded even if tests fail
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/ # Path to Maven test results

      # Step 7: Copy Maven Files to Host
      - name: Copy Maven Files to Host
        run: |
          docker cp app:/app/pom.xml ./pom.xml
          docker cp app:/app/.mvn ./.mvn

      # Step 8: Submit Dependency Graph
      - name: Update Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
